### ISSUE TITLE
Error loading corrupt .all file

### ISSUE THREAD

**Issue by soundsgood** [JonathanTaquet/Oe2sSLE#1]
Using version 0.0.7, the application hangs when trying to open an invalid .all file.
You have to use Task Manager to kill the app.

I have attached the log and the .all file.
[e2sSample.zip](https://github.com/JonathanTaquet/Oe2sSLE/files/185455/e2sSample.zip)

**Comment by JonathanTaquet** [comment]
Thank you for your report, following our [discussion on KorgForum](http://www.korgforums.com/forum/phpBB2/viewtopic.php?t=101780).

This is finally solved with release [v0.0.8](https://github.com/JonathanTaquet/Oe2sSLE/releases/tag/v0.0.8).

Display of a message indicating that error recovery occurred has been also [committed](https://github.com/JonathanTaquet/Oe2sSLE/commit/a155d936b681bf317c1cb4863f165c98234a9524)
