### ISSUE TITLE
Loading e2sSample.all takes way too long (Mac OS El Capitan, Python 3.5.1)

### ISSUE THREAD

**Issue by dctucker** [JonathanTaquet/Oe2sSLE#10]
It seems to load just very very slowly so I end up just force quitting it after waiting five minutes. Let me know if I can provide more information.

**Comment by JonathanTaquet** [comment]
Thank you for your report.
Can you find the Oe2sSLE.log file?
If yes, could you have a look at it and attach it to the Issue if there are usefull informations?
I will try in my side. Currently, I only have tested that the Editor was correctly starting on MacOS. I'll do more heavy testing soon.

**Comment by JonathanTaquet** [comment]
Sorry, I closed the Issue by inadvertently pressing the wrong button in the GitHub interface. I reopen it as it is not solved.

**Comment by dctucker** [comment]
So I'm not seeing anything weird in the log when initiating sample load, but I can help narrow it down maybe. I added some basic pagination to the code so it will only add 20 samples to the list after the try/catch block in import_all_sample(). Doing this makes allows me to playback the audio for the 20 samples shown in the list. However, if I set the start offset higher than about 400 the program starts to behave oddly, showing a black window when resizing (as noted in the other open issue).

It makes me believe this could be an issue with TK, but since I can't make it start after sample #400 I also think there's something weird about the get_next_free_sample_index() method of SampleList.

**Comment by lqlwle** [comment]
Hey, just wanted to leave a comment, that this happens here too – also on Mac OS El Capitan.
Python-process takes 100% of one of the cpu-cores and basically loads super slow. "Total Data Size" is increasing very slow. If I can help, let me know.

**Comment by JonathanTaquet** [comment]
Yes, it is really long... I think it is linked to how I use tkinter. I will have a look to see how to optimize it.

**Comment by lqlwle** [comment]
I left it running for quite a while and I have the feeling it becomes slower and slower the further it gets. I never made it to the end so far.

**Comment by lqlwle** [comment]
I have a question: Will this issue be addressed/solvable in the near future? I don't want to pressure at all since I know and really admire the effort that you put in here. I just need to know, because this issue sadly completely hinders me to use this software at the moment.

**Comment by JonathanTaquet** [comment]
Hi, I have an idea on how to solve this, but I'm not sure it will be sufficient...

I will simply not create the widgets (or just not show them) for every samples, but only for those that are displayed. Then I will update the display on scroll. I just hope that the problem will not be reported on the speed for the scrolling, by slowing it too much...

This would also fix the problem occurring on recent windows versions (see issue #12)
I hope I will have time to do it and commit a patch for this in the next week.

**Comment by JonathanTaquet** [comment]
Hello, just to inform you that I worked on this. I have nearly finished a version that I think stable. I need to do some more tests, and clean up the code. I think I will have a beta version that I will push on github next week.

**Comment by JonathanTaquet** [comment]
This issue should be fixed from 860cf7a0afe953bdf37a5f6620695df1b52bafb5
