### ISSUE TITLE
Compiling failed: Linter finds Error at Line 1088 col 86 in Oe2sSLE_GUI.py

### ISSUE THREAD

**Issue by lqlwle** [JonathanTaquet/Oe2sSLE#11]
Tried to compile the program myself but ran into an error. 

**Error at Line 1088 col 86 in Oe2sSLE_GUI.py**

Checked the code then with a linter and also the linter showed an error in this line.
Linter shows error in this block, behind the **lambda *args**.

```
for j in range(64):
            if self.activeStepsTrace[j]:
                self.activeSteps[j].trace_vdelete('w', self.activeStepsTrace[j])
            self.activeSteps[j].set(str(esli.sliceSteps[j]) if esli.sliceSteps[j] >= 0 else "Off")
            self.activeStepsTrace[j] =  self.activeSteps[j].trace('w', lambda *args, j=j: self._activeStepEdit(j))
```

**Comment by JonathanTaquet** [comment]
This should not occur if you use python 3.x and not python 2.7

**Comment by lqlwle** [comment]
ok thanks, that was the problem. Wasn't aware I was compiling with 2.7. Everything fine when compiling with 3.x

Thanks!
