### ISSUE TITLE
App crashes when playing a sample while another sample is still playing

### ISSUE THREAD

**Issue by flxkrmr** [JonathanTaquet/Oe2sSLE#15]
If I click on the play button of a sample, while another sample is still playing, the app crashes and does not respond any more. 
I'm running Oe2sSLE on Ubuntu 14.04.

**Comment by JonathanTaquet** [comment]
Hello, I'm not sure but it could be a pyaudio or portaudio problem...
The fix 145324bf81139f7015cdf98642894be011b6af43 should solve the issue.
