### ISSUE TITLE
Add smpl chunk to RIFF when exporting

### ISSUE THREAD

**Issue by johndoe46** [JonathanTaquet/Oe2sSLE#16]
1/ import wav with smpl chunk 
2/ save *.all file
3/ export wav file -> no more smpl chunk (korg loop points are ok though)

**Comment by JonathanTaquet** [comment]
Yes for sure, I voluntarily remove any chunck that is not used by the electribe, because, if I remember well, the electribe notify you with a load error when those chunks are present in the .all file. The electribe does the same when you import samples with it.
But if you need this feature, I can add an export option to translate the korg loop/slice points into smpl/cue chunks.

**Comment by johndoe46** [comment]
Ah ! I see... my experience with manually importing wavs (via sd card) with smpl chunks in the e2s was that they were simply ignored, sadly like a lot of hardware and software samplers do these days (and that's why I'm interested in Oe2SLE in the first place... because now I can finally enjoy my carefully looped wavs in the e2s, so thank you for that :) !). Of course, if having such chunks in the *.all file gives errors, you're obviously right to remove them at import.

However, when exporting, this would make perfect sense (for sampler interoperability) to translate loop points. I'm not sure about the need to translate slice points because I don't know any other sampler that would use them, but loop points, yes, I would definitely love a smpl translation for those since my samples often go back and forth between the e2s and Renoise.

Maybe it could be an option of e2s_sample.write() ?

**Comment by JonathanTaquet** [comment]
I'm working on it. It should be done tomorrow.
I think that slice points may also be interesting if you want to export sliced samples to use them in a daw (for instance).

**Comment by JonathanTaquet** [comment]
Commits 047df9ed36c7600363c03688abf4cf168f26c9c4 and a5fa14184c853bbd042ac2e95300c11dfd607bb8 should do the job.

The export of smpl/cue chunks is currently activated for all exported samples.

I will see later to add an option file + an interface to set options. It will let the possibility to disable the export of smpl/cue chunks if one wants.

**Comment by johndoe46** [comment]
Works like a charm ! Thank you :-)

**Comment by JonathanTaquet** [comment]
Ok, nice. Thank you.
