### ISSUE TITLE
MacOSX / Usage of pad scrolling crashes Oe2SLE

### ISSUE THREAD

**Issue by johndoe46** [JonathanTaquet/Oe2sSLE#20]
```
(myenv) Mickael-Desfrenes:Oe2sSLE-taquet $ python Oe2sSLE_GUI.py
Traceback (most recent call last):
  File "Oe2sSLE_GUI.py", line 2350, in <module>
    app.mainloop()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1140, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by JonathanTaquet** [comment]
Are you using [official python distribution 3.5.3](https://www.python.org/downloads/release/python-353/) with [correct tcl/tk version](https://www.python.org/download/mac/tcltk/)?

**Comment by johndoe46** [comment]
I'm using python 3.5.3 from this package: https://www.python.org/ftp/python/3.5.3/python-3.5.3-macosx10.6.pkg

```
(myenv) Mickael-Desfrenes:Oe2sSLE-taquet mickaeldesfrenes$ python --version
Python 3.5.3
```

Do I have to install something else ?

**Comment by rmoetwil** [comment]
I had the same issue when trying this project against Python 3.6.
I switched back to Python 3.5 and all was working fine.

I used python-3.5.2-macosx10.6.pkg
pyaudio 0.2.9

**Comment by JonathanTaquet** [comment]
You should also probably install ActiveTcl 8.5.18.0 as mentioned [here](https://www.python.org/download/mac/tcltk/#activetcl-8-5-18-0). This is what I did in order to build a release that was working on MacOS X Mountain Lion [see that discussion on Korg Forums](http://www.korgforums.com/forum/phpBB2/viewtopic.php?p=710743#710743). See also Issue #2.

**Comment by johndoe46** [comment]
None of these helped... I'll try again later.

**Comment by JonathanTaquet** [comment]
Do you also have the crash when you use the prebuilt release version?

**Comment by johndoe46** [comment]
No, the prebuilt version 0.20 works fine (seems to have better performance too). Still not sure why it's not fine from source too but at least now it's usable. Thanks !
