### ISSUE TITLE
Stereo checkbox won't update until panel scrolled

### ISSUE THREAD

**Issue by muranyia** [JonathanTaquet/Oe2sSLE#21]
After converting a stereo sample into mono, the checkbox stays checked and changes to unchecked immediately when the whole panel is scrolled.

**Comment by JonathanTaquet** [comment]
Could you detail which version and OS you are using?
I could not reproduce this, neither on windows nor on macos.

**Comment by muranyia** [comment]
This is version 0.2.0 from git running on Ubuntu 16.04.2 LTS amd64.

**Comment by JonathanTaquet** [comment]
It should be ok now.
