### ISSUE TITLE
Windows binary is blocked by Antivirus

### ISSUE THREAD

**Issue by shathor** [JonathanTaquet/Oe2sSLE#22]
Avira Antivirus gives a security alert after downloading the windows binary version 0.2.0:

![blocked](https://user-images.githubusercontent.com/10561355/28228115-5f2b8c50-68dd-11e7-9e30-5bd1235d43d5.PNG)

**Comment by JonathanTaquet** [comment]
Probably a false positive...
I will update pyinstaller before building next release. I hope it will solve your issue

**Comment by shathor** [comment]
I'll try it out soonish.
Building and running the source works fine.

**Comment by JonathanTaquet** [comment]
I know I'm late, but is it ok, now?

**Comment by shathor** [comment]
Yes. I tried newest version 0.2.1. Issue can be closed.
