### ISSUE TITLE
exporting an one individual wavs

### ISSUE THREAD

**Issue by JosephHeller** [JonathanTaquet/Oe2sSLE#23]
I am having trouble exporting wavs from the sample manager. I can export all wavs but i get this message when i try to just export one wav:
Error message:
'samplelist object' has no attribute export_opts 
It does then make the wav file but it has nothing in it and does not play. 
This did not happen with the previous version of the software that i had. 
I am using windows 10 
I really like this app and much prefer it to the other version of this prgram that i have used.
I have temporarily switched back to 1.32 which is working correctly.

**Comment by JonathanTaquet** [comment]
It is fixed, and will be integrated in next release

**Comment by JonathanTaquet** [comment]
It should be ok, now
