### ISSUE TITLE
Number gaps between samples

### ISSUE THREAD

**Issue by flxkrmr** [JonathanTaquet/Oe2sSLE#25]
Is it possible to have number gaps between samples, e.g. one sample has the "#Num" 50 and the next 70?

At the moment it seems that it is possible in the gui, but the gaps are filled when the file is saved.

I'd like to store my samples sorted by type, but I think if I change the sample number, the electribe does not find the samples anymore, if I used them in a track. Please correct me if I'm wrong. Because of this I want to leave number gaps between each sample type group to add samples later. 
Any suggestion on this?

**Comment by JonathanTaquet** [comment]
> Is it possible to have number gaps between samples, e.g. one sample has the "#Num" 50 and the next 70?

Yes it is

> At the moment it seems that it is possible in the gui, but the gaps are filled when the file is saved.

What do you mean ? if I do what you say: add a sample, set it to #Num 50, add another one and set it to #Num 70, save the file, the gap is still there.

**Comment by JonathanTaquet** [comment]
Hum ok I see...

If you manually edit the #Num with a value higher that the next one, the #Num are not properly refreshed in the GUI.

As I have chosen to implement it, you should not be able to change the order of the sample by editing #Num, so if a first sample is number 1, a second is number 3, if you set the first sample number to 5, the second will be 6 (this is voluntary, but maybe not so user friendly... I'll think about changing this)

Nevertheless I agree that the numbers should be refreshed after one is edited. It is working properly as soon as you open a file, but when you just open the software it does not always work properly.
I have to investigate

Just an advice: do not edit sample number with your keyboard

**Comment by flxkrmr** [comment]
Ok, thanks!

**Comment by JonathanTaquet** [comment]
this bug should be fixed in the last release
