### ISSUE TITLE
The receiver jonathan.taquet<AT>gmail.com does not accept payments in this Currency

### ISSUE THREAD

**Issue by layk** [JonathanTaquet/Oe2sSLE#26]
Hi
I was trying to donate and pledgie gives me USD dollars are not accepted and no choice to use any other.

**Comment by JonathanTaquet** [comment]
Hi
Thank You to mention it... I forgot to activate $USD in my paypal account... hemm... (this is done now)

Nevertheless, thank you for having tried to support! ^^

**Comment by JonathanTaquet** [comment]
It seems that the issue is solved, as I received your donation! thank you again for your support.
