### ISSUE TITLE
Error: unpack requires a bytes object of length 8

### ISSUE THREAD

**Issue by thisiscan** [JonathanTaquet/Oe2sSLE#9]
Hey Brakio this is Can from the Korgforum.
OS is v0.0.11.
![screenshot 24](https://cloud.githubusercontent.com/assets/22156667/18449032/ceaf111e-792d-11e6-8ac9-23de4064c903.png)
LOG: C:\Users\Admin\AppData\Local\Temp_MEI15762\RIFF__init__.py:248: UserWarning: 'RIFF' chunk contains an ignored truncaded chunk
-- Logger closed --

**Comment by JonathanTaquet** [comment]
Hey Can, thank you.
Is it possible to provide the wav sample file?
(you can drag & drop it in the write area to attach it to your message)

**Comment by thisiscan** [comment]
Filetype is not supported, instead try this. http://s000.tinyupload.com/?file_id=83479467912296959289

**Comment by JonathanTaquet** [comment]
Thank you. I'll have a look as soon as possible ;)

**Comment by JonathanTaquet** [comment]
Ok, thank you. It is fixed with commits f26b0980a53a8b2a919a7c94d12d065afb15bd03 and 46a0612acfc1c165345285978dedd7fd0d1aef24
